database:
  host: "cluster0.gkboq8o.mongodb.net"
  user: "admin"
  password: "8dEEFgSldfSerTHO"
  timeout: 10
  dbname: "testing"

node:
  chainId: "channel"
  endpoint: "http://0.0.0.0:26657"
  coinType: 60
  prefixAddress: "cosmos"
  tokenSymbol: "token"
