// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: node/rpc/proto/p2p.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetListPeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetListPeerRequest) Reset() {
	*x = GetListPeerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_rpc_proto_p2p_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListPeerRequest) ProtoMessage() {}

func (x *GetListPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_rpc_proto_p2p_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListPeerRequest.ProtoReflect.Descriptor instead.
func (*GetListPeerRequest) Descriptor() ([]byte, []int) {
	return file_node_rpc_proto_p2p_proto_rawDescGZIP(), []int{0}
}

type GetListPeerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListPeer []*GetListPeerResponse_Peer `protobuf:"bytes,1,rep,name=ListPeer,proto3" json:"ListPeer,omitempty"`
}

func (x *GetListPeerResponse) Reset() {
	*x = GetListPeerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_rpc_proto_p2p_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListPeerResponse) ProtoMessage() {}

func (x *GetListPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_rpc_proto_p2p_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListPeerResponse.ProtoReflect.Descriptor instead.
func (*GetListPeerResponse) Descriptor() ([]byte, []int) {
	return file_node_rpc_proto_p2p_proto_rawDescGZIP(), []int{1}
}

func (x *GetListPeerResponse) GetListPeer() []*GetListPeerResponse_Peer {
	if x != nil {
		return x.ListPeer
	}
	return nil
}

type GetListPeerResponse_Peer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *GetListPeerResponse_Peer) Reset() {
	*x = GetListPeerResponse_Peer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_rpc_proto_p2p_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListPeerResponse_Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListPeerResponse_Peer) ProtoMessage() {}

func (x *GetListPeerResponse_Peer) ProtoReflect() protoreflect.Message {
	mi := &file_node_rpc_proto_p2p_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListPeerResponse_Peer.ProtoReflect.Descriptor instead.
func (*GetListPeerResponse_Peer) Descriptor() ([]byte, []int) {
	return file_node_rpc_proto_p2p_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetListPeerResponse_Peer) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

var File_node_rpc_proto_p2p_proto protoreflect.FileDescriptor

var file_node_rpc_proto_p2p_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x32, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x68, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x50, 0x65, 0x65, 0x72, 0x52, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x1a, 0x1a,
	0x0a, 0x04, 0x50, 0x65, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x32, 0x48, 0x0a, 0x0a, 0x50, 0x65,
	0x65, 0x72, 0x54, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x32, 0x35, 0x2d, 0x6c, 0x61, 0x62, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x6e, 0x69, 0x6e, 0x67, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2d, 0x6e, 0x6f, 0x64,
	0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_node_rpc_proto_p2p_proto_rawDescOnce sync.Once
	file_node_rpc_proto_p2p_proto_rawDescData = file_node_rpc_proto_p2p_proto_rawDesc
)

func file_node_rpc_proto_p2p_proto_rawDescGZIP() []byte {
	file_node_rpc_proto_p2p_proto_rawDescOnce.Do(func() {
		file_node_rpc_proto_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(file_node_rpc_proto_p2p_proto_rawDescData)
	})
	return file_node_rpc_proto_p2p_proto_rawDescData
}

var file_node_rpc_proto_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_node_rpc_proto_p2p_proto_goTypes = []interface{}{
	(*GetListPeerRequest)(nil),       // 0: GetListPeerRequest
	(*GetListPeerResponse)(nil),      // 1: GetListPeerResponse
	(*GetListPeerResponse_Peer)(nil), // 2: GetListPeerResponse.Peer
}
var file_node_rpc_proto_p2p_proto_depIdxs = []int32{
	2, // 0: GetListPeerResponse.ListPeer:type_name -> GetListPeerResponse.Peer
	0, // 1: PeerToPeer.GetListPeer:input_type -> GetListPeerRequest
	1, // 2: PeerToPeer.GetListPeer:output_type -> GetListPeerResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_node_rpc_proto_p2p_proto_init() }
func file_node_rpc_proto_p2p_proto_init() {
	if File_node_rpc_proto_p2p_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_node_rpc_proto_p2p_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListPeerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_rpc_proto_p2p_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListPeerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_rpc_proto_p2p_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListPeerResponse_Peer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_node_rpc_proto_p2p_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_rpc_proto_p2p_proto_goTypes,
		DependencyIndexes: file_node_rpc_proto_p2p_proto_depIdxs,
		MessageInfos:      file_node_rpc_proto_p2p_proto_msgTypes,
	}.Build()
	File_node_rpc_proto_p2p_proto = out.File
	file_node_rpc_proto_p2p_proto_rawDesc = nil
	file_node_rpc_proto_p2p_proto_goTypes = nil
	file_node_rpc_proto_p2p_proto_depIdxs = nil
}
